# Generated by Django 4.0.4 on 2022-05-17 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0002_rename_price_product_unit_price_address_zip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
    ]
