# Generated by Django 4.0.4 on 2022-06-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0004_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
