# Generated by Django 4.0.4 on 2022-06-05 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0009_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
